apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sectigo-issuer.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sectigo-issuer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sectigo-issuer.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "sectigo-issuer.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
