# permissions to approve all sectigo.opensource.io requests
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-approve:sectigo-opensource-io
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - signers
  verbs:
  - approve
  resourceNames:
  - sectigoissuers.sectigo.opensource.io/*
  - sectigoclusterissuers.sectigo.opensource.io/*
