---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests/status
  verbs:
  - patch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/status
  verbs:
  - patch
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - sectigoclusterissuers.sectigo.opensource.io/*
  - sectigoissuers.sectigo.opensource.io/*
  resources:
  - signers
  verbs:
  - sign
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - sectigo.opensource.io
  resources:
  - sectigoclusterissuers
  - sectigoissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sectigo.opensource.io
  resources:
  - sectigoclusterissuers/status
  - sectigoissuers/status
  verbs:
  - patch
