apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-by-sectigoissuer
spec:
  commonName: certificate-by-sectigoissuer.example.com
  secretName: certificate-by-sectigoissuer
  issuerRef:
    name: sectigoissuer-sample
    group: sectigo.opensource.io
    kind: SectigoIssuer
