## Append samples of your project ##
resources:
- sectigo_v1alpha1_sectigoissuer.yaml
- sectigo_v1alpha1_sectigoclusterissuer.yaml
# +kubebuilder:scaffold:manifestskustomizesamples

- certificate_clusterissuer.yaml
- certificate_issuer.yaml
- certificaterequest_clusterissuer.yaml
- certificaterequest_issuer.yaml
- secret_clusterissuer.yaml
- secret_issuer.yaml
