apiVersion: sectigo.opensource.io/v1alpha1
kind: SectigoClusterIssuer
metadata:
  labels:
    app.kubernetes.io/name: sectigo-issuer
    app.kubernetes.io/managed-by: kustomize
  name: sectigoclusterissuer-sample
spec:
  authSecretName: "sectigoclusterissuer-sample-credentials"
  url: "http://sectigo.opensource.io/api/v1"
